/**
 * categoryIcons.js — Maps icon_category and AI_primary_field values to icon image paths.
 *
 * Icons are stored in /public/icons/categories/{category}.png
 * Generated by generate_icons.py using Stable Diffusion XL.
 *
 * getIconPath(node) resolves the best icon for a given paper node:
 *   1. Specific icon_category match (e.g., "atlas-detector")
 *   2. Fallback to AI_primary_field generic icon (e.g., "Quantum Chromodynamics")
 *   3. Final fallback to generic experiment icon
 */

// Specific sub-category icons (generated from paper abstracts)
// Keys must match the icon_category values from classify_icon_category.py
export const CATEGORY_ICONS = {
  // ── LHC Detectors ──
  "atlas-detector": "categories/atlas-detector.png",
  "cms-detector": "categories/cms-detector.png",
  "lhcb-detector": "categories/lhcb-detector.png",
  "alice-detector": "categories/alice-detector.png",

  // ── Tevatron ──
  "tevatron-cdf": "categories/tevatron-cdf.png",
  "tevatron-d0": "categories/tevatron-d0.png",
  "tevatron": "categories/tevatron.png",

  // ── HERA ──
  "hera-h1": "categories/hera-h1.png",
  "hera-zeus": "categories/hera-zeus.png",
  "hera": "categories/hera.png",

  // ── B-factories ──
  "belle-experiment": "categories/belle-experiment.png",
  "babar-experiment": "categories/babar-experiment.png",
  "kekb": "categories/kekb.png",

  // ── LEP ──
  "lep-delphi": "categories/lep-delphi.png",
  "lep-opal": "categories/lep-opal.png",
  "lep-aleph": "categories/lep-aleph.png",
  "lep-l3": "categories/lep-l3.png",
  "lep": "categories/lep.png",

  // ── Neutrino experiments ──
  "super-kamiokande": "categories/super-kamiokande.png",
  "miniboone": "categories/miniboone.png",
  "icecube": "categories/icecube.png",
  "sno": "categories/sno.png",
  "t2k": "categories/t2k.png",
  "nova-neutrino": "categories/nova-neutrino.png",
  "dune": "categories/dune.png",
  "double-chooz": "categories/double-chooz.png",
  "daya-bay": "categories/daya-bay.png",
  "borexino": "categories/borexino.png",
  "antares": "categories/antares.png",
  "minos": "categories/minos.png",

  // ── Heavy ion ──
  "rhic-star": "categories/rhic-star.png",
  "rhic-phenix": "categories/rhic-phenix.png",
  "rhic": "categories/rhic.png",

  // ── Fixed target / other ──
  "na62": "categories/na62.png",
  "na48-na49": "categories/na48-na49.png",
  "compass": "categories/compass.png",
  "lhc-forward": "categories/lhc-forward.png",
  "fermilab-fixed": "categories/fermilab-fixed.png",

  // ── Dark matter detectors ──
  "xenon-dm": "categories/xenon-dm.png",
  "lux-dm": "categories/lux-dm.png",
  "pandax-dm": "categories/pandax-dm.png",
  "cdms-dm": "categories/cdms-dm.png",
  "admx-axion": "categories/admx-axion.png",

  // ── Gravitational waves / cosmic ray / space ──
  "ligo-gw": "categories/ligo-gw.png",
  "auger-cosmic": "categories/auger-cosmic.png",
  "fermi-lat": "categories/fermi-lat.png",
  "hubble-telescope": "categories/hubble-telescope.png",
  "jwst-telescope": "categories/jwst-telescope.png",
  "planck-satellite": "categories/planck-satellite.png",

  // ── Higgs physics ──
  "higgs-discovery": "categories/higgs-discovery.png",
  "higgs-properties": "categories/higgs-properties.png",
  "higgs-search": "categories/higgs-search.png",
  "higgs-boson": "categories/higgs-boson.png",

  // ── Top quark ──
  "top-quark": "categories/top-quark.png",

  // ── Electroweak ──
  "w-boson": "categories/w-boson.png",
  "z-boson": "categories/z-boson.png",
  "electroweak-precision": "categories/electroweak-precision.png",
  "diboson": "categories/diboson.png",

  // ── QCD / Jets ──
  "jet-production": "categories/jet-production.png",
  "jet-substructure": "categories/jet-substructure.png",

  // ── Heavy quarks & exotic hadrons ──
  "charmonium": "categories/charmonium.png",
  "bottomonium": "categories/bottomonium.png",
  "tetraquark": "categories/tetraquark.png",
  "pentaquark": "categories/pentaquark.png",
  "exotic-hadrons": "categories/exotic-hadrons.png",
  "quarkonium": "categories/quarkonium.png",

  // ── B / charm / kaon / pion physics ──
  "b-meson-cp": "categories/b-meson-cp.png",
  "b-meson-decay": "categories/b-meson-decay.png",
  "charm-physics": "categories/charm-physics.png",
  "kaon-physics": "categories/kaon-physics.png",
  "pion-physics": "categories/pion-physics.png",
  "baryon-spectroscopy": "categories/baryon-spectroscopy.png",

  // ── Neutrino topics ──
  "neutrino-oscillation": "categories/neutrino-oscillation.png",
  "neutrino-cross-section": "categories/neutrino-cross-section.png",
  "neutrino-mass": "categories/neutrino-mass.png",
  "sterile-neutrino": "categories/sterile-neutrino.png",
  "neutrino-astro": "categories/neutrino-astro.png",

  // ── Dark matter topics ──
  "dark-matter-direct": "categories/dark-matter-direct.png",
  "dark-matter-collider": "categories/dark-matter-collider.png",
  "dark-matter-indirect": "categories/dark-matter-indirect.png",
  "dark-matter-model": "categories/dark-matter-model.png",
  "dark-matter": "categories/dark-matter.png",

  // ── SUSY ──
  "susy-search": "categories/susy-search.png",
  "susy-spectrum": "categories/susy-spectrum.png",
  "susy": "categories/susy.png",

  // ── Axion ──
  "axion-search": "categories/axion-search.png",
  "axion": "categories/axion.png",

  // ── Heavy ion topics ──
  "quark-gluon-plasma": "categories/quark-gluon-plasma.png",
  "heavy-ion-flow": "categories/heavy-ion-flow.png",
  "heavy-ion": "categories/heavy-ion.png",

  // ── QCD topics ──
  "parton-distribution": "categories/parton-distribution.png",
  "fragmentation": "categories/fragmentation.png",
  "qcd-resummation": "categories/qcd-resummation.png",
  "nlo-nnlo": "categories/nlo-nnlo.png",

  // ── Lattice / Monte Carlo ──
  "lattice-qcd": "categories/lattice-qcd.png",
  "monte-carlo-sim": "categories/monte-carlo-sim.png",

  // ── Detector & accelerator R&D ──
  "detector-rd": "categories/detector-rd.png",
  "accelerator-rd": "categories/accelerator-rd.png",

  // ── Cosmic / CMB / gravitational ──
  "cosmic-ray": "categories/cosmic-ray.png",
  "cmb-observation": "categories/cmb-observation.png",
  "gravitational-wave": "categories/gravitational-wave.png",

  // ── Precision measurements ──
  "muon-g2": "categories/muon-g2.png",
  "edm-measurement": "categories/edm-measurement.png",
  "alpha-qed": "categories/alpha-qed.png",

  // ── BSM / rare decays ──
  "rare-decay": "categories/rare-decay.png",
  "bsm-search": "categories/bsm-search.png",

  // ── Broad fallbacks ──
  "collider-general": "categories/collider-general.png",
  "neutrino-general": "categories/neutrino-general.png",
  "qcd-general": "categories/qcd-general.png",
  "electroweak-general": "categories/electroweak-general.png",
  "hadron-general": "categories/hadron-general.png",
  "lepton-general": "categories/lepton-general.png",
  "nuclear-general": "categories/nuclear-general.png",
  "cosmology-general": "categories/cosmology-general.png",
  "astroparticle": "categories/astroparticle.png",
};

// Fallback icons by AI_primary_field (for papers with no specific icon_category)
export const FIELD_FALLBACK_ICONS = {
  "Quantum Chromodynamics": "categories/qcd-general.png",
  "Standard Model": "categories/collider-general.png",
  "Particle Physics": "categories/collider-general.png",
  "Neutrino Physics": "categories/neutrino-general.png",
  "Dark Matter / Energy": "categories/dark-matter.png",
  "String Theory": "categories/collider-general.png",
  "Supersymmetry": "categories/susy.png",
  "Heavy Ion Physics": "categories/heavy-ion.png",
  "Quantum Electrodynamics": "categories/lepton-general.png",
  "Cosmology": "categories/cosmology-general.png",
  "Lattice Gauge Theory": "categories/lattice-qcd.png",
  "High Energy Physics": "categories/collider-general.png",
  "Nuclear Physics": "categories/nuclear-general.png",
  "Astrophysics": "categories/astroparticle.png",
  "Astroparticle Physics": "categories/astroparticle.png",
};

/**
 * Resolve the icon path for a paper node.
 * Returns the path relative to /public/icons/, or null if no icon available.
 *
 * @param {Object} node - Paper node with iconCategory and primaryField properties
 * @returns {string|null} Icon path relative to /public/icons/
 */
export function getIconPath(node) {
  // 1. Try specific icon_category
  if (node.iconCategory && CATEGORY_ICONS[node.iconCategory]) {
    return CATEGORY_ICONS[node.iconCategory];
  }

  // 2. Try AI_primary_field fallback
  if (node.primaryField && FIELD_FALLBACK_ICONS[node.primaryField]) {
    return FIELD_FALLBACK_ICONS[node.primaryField];
  }

  // 3. Generic fallback
  return "categories/collider-general.png";
}

/**
 * Check if a node should display an icon (only experimental/phenomenological papers).
 * @param {Object} node - Paper node with paperNature property
 * @returns {boolean}
 */
export function shouldShowIcon(node) {
  return node.paperNature === "experimental" || node.paperNature === "phenomenological";
}
